#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## launch kitty with bspwm config


if [ "$1" == "--float" ]; then
	kitty --class 'kitty-float,kitty-float'
elif [ "$1" == "--full" ]; then
	kitty --class 'Fullscreen,Fullscreen' \
			  -o window.startup_mode=fullscreen \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=14
else
	kitty
fi
