-- require("catppuccin").setup({
--   flavour = "macchiato", -- latte, frappe, macchiato, mocha
--   transparent_background = true,
--   integrations = {
--     cmp = true,
--     gitsigns = true,
--     nvimtree = true,
--     telescope = true,
--     treesitter = true,
--     indent_blankline = {
--       enabled = true,
--       colored_indent_levels = true,
--     },
--     -- For more plugins integrations please scroll down (https://github.com/catppuccin/nvim#integrations)
--   },
-- })
--
-- -- setup must be called before loading
-- vim.cmd.colorscheme "catppuccin"
